### PR TITLE
Test enhancement

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log
- Upgrade PHPUnit version to `^6.5`.
- Add `php: >=7.0` in require block and define this in `composer.json`.
- Add the test classes namespace in `autoload-dev` block and define this in `composer.json`.

### CODE REVIEW

**Comment by peter279k** [comment]
@DivineOmega, the Travis CI build work is failed.

It looks like the `php-7.0` test is failed because the `cURL` handshake is failed.

```php
GuzzleHttp\Exception\ConnectException: cURL error 35: gnutls_handshake() failed: Handshake failed.
```
Do you have any idea about this solution?

**Comment by DivineOmega** [comment]
@peter279k This is actually a bug with Travis not being able to perform PHP Curl requests to HTTPS URLs in PHP 7.0.

See here for more information: https://github.com/travis-ci/travis-ci/issues/6339

This was why PHP 7.0 is not in the `.travis.yml` file.

**Comment by DivineOmega** [comment]
Feel free to just remove PHP 7.0 from your `.travis.yml`.

**Comment by peter279k** [comment]
@DivineOmega, thank you for your reply.

You mean we just skip the `php-7.0` test in Travis CI build.

How can we ensure the `php-7.0` can be worked well? Perhaps this package will add `php: "^7.1"` for `require` block in `composer.json`.

**Comment by DivineOmega** [comment]
@peter279k I think we might have to just skip PHP 7.0. I don't want to increase the minimum version the package supports, as I know many web applications are still (unfortunately) using PHP 5.6.

I would suggest just skipping PHP 7.0 for now to get this merged.

**Comment by DivineOmega** [comment]
Thanks!

**Pull request merged**
